blokadaorg/blokada

app/src/main/kotlin/core/Filters.kt

The existing definition of cacheTTLMillis was specified in centiseconds, rather than milliseconds, leading to a cache file update 10 times per day. This updates that to be once a day, which should be sufficient for most people, at least until a tunable parameter can be specified.
This 10x daily refreshing was responsible for some ridiculous data usage. Although not directly the issue for, e.g., #195, this certainly exacerbates those situations.

Set cache update timeout to one day

---

app/src/tunnel/kotlin/tunnel/VpnConfigurator.kt

This should resolve issue #94. The issue was that when the `VpnConfigure.Builder` is not given any IPv6 address as a `addRoute` or `addDnsServer` call, it blocks all IPv6 communication by default. This should not break the blocking functionality since dnsjava supports AAAA queries as well and the `question.name` (see `Proxy.kt:55`) remains included in any case, which allows Blokada to block any requests to disallowed hostnames.

Enable basic IPv6 support - DNS results now include AAAA records

---

app/src/legacy/kotlin/core/Dns.kt
app/src/legacy/kotlin/gs/environment/AConnectivity.kt
app/src/legacy/res/layout/view_dnsadd.xml
app/src/tunnel/kotlin/tunnel/Main.kt
app/src/tunnel/kotlin/tunnel/Proxy.kt
app/src/tunnel/kotlin/tunnel/VpnConfigurator.kt

Working towards a solution for #198.
This PR should pave the way for integrating [dnscrypt-proxy](https://github.com/jedisct1/dnscrypt-proxy) as a local cache/resolver running on the device, controlled by Blokada. To let it run without having root we need to use an unprivileged port (that is, a port >=1024).

Patch for using DNS servers on nonstandard ports

---

app/src/legacy/AndroidManifest.xml

Update the AndroidManifest so that long-pressing the quick settings tile navigates to the main activity (instead of opening the app info page)

Open main activity on QS tile long press

---

app/src/flavor-adblocker/kotlin/adblocker/ListWidget.kt
app/src/flavor-adblocker/kotlin/flavor/Module.kt
app/src/legacy/AndroidManifest.xml
app/src/legacy/kotlin/core/KeepAlive.kt
app/src/legacy/kotlin/notification/ANotificationUtils.kt
app/src/legacy/kotlin/notification/ANotificationsToggleService.kt
app/src/legacy/kotlin/notification/ANotificationsWhitelistService.kt
app/src/legacy/res/layout/view_keepalive_collapsed.xml
app/src/legacy/res/layout/view_keepalive_expanded.xml
app/src/legacy/res/layout/view_list_widget.xml
app/src/legacy/res/values/strings_notification.xml
app/src/legacy/res/xml/list_widget_info.xml

I redesigned the permanent notification(keep alive) with the following changes:
- There is now a button to (de-)activate Blokada
- It's now extensible to display more information
- It shows the unique domains in the 10 last blocked requests
- Its design fits better to the overall look of Blokada.
Multiple users in the Telegram group wanted a widget with the same layout and informations, so I added this as well.
Fixes #97

Permanent notification rework and additional widget

---

README.md

The link to report a phishing attempt is broken on the current `README`.
This updates the broken link with a working one.

Fix broken link on readme

---

app/src/legacy/kotlin/core/AllAppsDashboardSectionVB.kt

Fixed empty views after all predefined apps are removed from whitelist

Fixed empty views after all predefined apps are removed from whitelist

---

app/src/full/kotlin/core/bits/menu/advanced/MenuAdvanced.kt
app/src/full/kotlin/tunnel/BlockaTunnelFiltering.kt
app/src/full/kotlin/tunnel/DnsAnswer.kt
app/src/full/kotlin/tunnel/DnsAnswerState.kt
app/src/full/kotlin/tunnel/DnsProxy.kt
app/src/ui-blokada/kotlin/core/Tunnel.kt
app/src/ui-blokada/kotlin/core/bits/Slots.kt
app/src/ui-blokada/res/values/strings_panel.xml

There were some users reporting that Blokada didn't block ads on ColorOS. Returning a invalid address instead of "host not found" seems to help.

implemented alternative DNS query answer as workaround for ColorOS

---

app/src/ui-blokada/kotlin/core/bits/Slots.kt
app/src/ui-blokada/res/values/strings_panel.xml

Applications can't utilise all the available RAM of the device, the Android system limits it. This value is the maxMemory. It is now showed on the UI to provide better explanation why users can't load all the lists.

Providing memory limitation per app

---

app/src/tun-local/kotlin/tunnel/Model.kt
app/src/ui-blokada/res/values/strings_bits.xml
app/src/ui-blokada/res/values/strings_panel.xml

Based on a list with 1.327.728 unique hostnames, the average hostname lenght is 20,41 char long. As fractions aren't supported, it's better to round up to 21.
Unicode characters use 2 bytes.
I ran a test for a few days to see how much RAM one hostname consumes in average, it is around 130 bytes

Changing memory related values

---

app/src/core/kotlin/adblocker/RequestLogger.kt
app/src/tun-local/kotlin/tunnel/TunnelMain.kt
app/src/ui-blokada/kotlin/core/Tunnel.kt
app/src/ui-blokada/kotlin/core/bits/AdsDashboardSectionVB.kt
app/src/ui-blokada/kotlin/core/bits/menu/adblocking/HostsLogVB.kt
app/src/ui-blokada/res/values/strings_logger.xml

Update the "Disabled" request logging option to also block logging in memory / local storage. Added a new option, "Log to internal storage only", which is selected by default, and matches the current functionality.
Resolves issue #495 .

Update logic to block request logging

---

app/src/ui-blokada/res/values/strings_panel.xml

Google calls DoH and DoT as 'Private DNS' in system's Settings - 'Network & Internet', using the same term for 3rd party DNS servers may confuse the users

Replacing 'Private DNS' with 'Custom DNS'

---

app/src/ui-blokada/kotlin/notification/ANotificationUtils.kt

This fixes a nasty crash when toIndex in subList goes out of range:
(Cut down for brevity)
```
E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service core.KeepAliveService@8ecb0ab with Intent { act=KeepAliveService cmp=org.blokada.origin.alarm/core.KeepAliveService }: java.lang.IndexOutOfBoundsException: toIndex = 15
[...]
E AndroidRuntime: 	at java.util.ArrayList.subListRangeCheck(ArrayList.java:1016)
E AndroidRuntime: 	at java.util.ArrayList.subList(ArrayList.java:1008)
E AndroidRuntime: 	at notification.UsefulKeepAliveNotification$1.invoke(ANotificationUtils.kt:184)
E AndroidRuntime: 	at notification.UsefulKeepAliveNotification$1.invoke(ANotificationUtils.kt:160)
E AndroidRuntime: 	at notification.BlokadaNotificationManager.getNotification(ANotificationUtils.kt:71)
``` …

notification: Take at most 15 blocked history items

---

app/src/ui-blokada/kotlin/core/bits/menu/adblocking/Sections.kt

There is currently a problem, in the hostlog:
If you open a slot and scroll down the list is expanded and the last opened Slot-instance isn't attached anymore. This causes all slots to stay closed if you click them because the SlotMutex tries to close the detached Slot which isn't possible.

Fixed SlotMutex "freezing" with all slots closed

---

app/build.gradle
build.gradle

It's annoying to have to deal with every time the project is cloned. Hopefully it works right for you. If not, just mess around with it until it does (because I have no clue how yours is set up).
I put this together by merging usages of two of my favorite projects:
- https://github.com/Adamantcheese/Kuroba/blob/multi-feature/Kuroba/app/build.gradle#L170
- https://github.com/TwidereProject/Twidere-Android/blob/master/twidere/build.gradle#L72

Fix missing signingConfig errors for cloners

---

app/src/full/kotlin/tunnel/BlockaTunnelFiltering.kt

Don't know how this one slipped through my initial testing but sometimes when using cname blocking with Blokada Plus a BufferOverflowException would be thrown.
This was caused by the generated answer for the blocked cname sometimes being larger then the original answer and by that breaking the limit set on the buffer. This is fixed by setting the limit before copying the new content into the package buffer.

fixed a bufferoverflow exception in Blokada Plus caused by cname blocking

---

android5/app/src/main/java/repository/PackDataSource.kt

Currently the extended list is used even the standard is intended.

Correcting Phishing Army's standard list's link

---

fastlane/metadata/android/en-US/full_description.txt

As 5 is the recommended version (https://community.blokada.org/t/blokada-5-for-android-is-now-stable/3692) this information should be displayed in version 4.x in F-Droid.
These changes the fastlane metadata it will only propagate to F-Droid after creating a new tag (which of course needs to be built at F-Droid).

Recommend Blokada 5 in the 4 metadata for F-Droid

---

android5/app/src/main/java/repository/AppRepository.kt

Based on issue [#847](https://github.com/blokadaorg/blokada/issues/847)

Bypass TomTom AmiGO by default

---

android5/app/src/main/java/repository/AppRepository.kt

Threema recently published their app in the Huawei AppGallery. Those
builds have a different package name compared to Google Play:
- ch.threema.app.hms
- ch.threema.app.work.hms
Bypass those as well.

Bypass Threema HMS builds as well

---

android5/app/src/main/java/repository/DnsDataSource.kt

Support the other two Cloudflare DNS services over https. The DNS paths can be looked up here: https://developers.cloudflare.com/1.1.1.1/1.1.1.1-for-families/setup-instructions/dns-over-https

Support for Cloudflare DNS over HTTPS for Families

---

android5/app/src/main/java/repository/DnsDataSource.kt
blocka_engine/blocka_dns/src/runtime.rs
ios/App/Model/DnsModel.swift

DoH resolver of [Digital Society Switzerland](https://www.digitale-gesellschaft.ch/) don't support DoH based on JSON. Although it was never officially supported, it had worked. Users of Blokada who select these name resolvers are facing name resolution issues.
As soon as #927 is implemented these DoH resolvers can be enabled again.

Remove non-JSON DoH resolver until RFC 8484 is supported

---

android5/app/src/main/java/repository/DnsDataSource.kt

As I know only json based query is supported here from this commend: #836 (comment), you can verify that it supports json query by visiting these urls:
- https://doh.chi.ahadns.net/dns-query?name=blokada.org&type=a&ct=application/dns-json
- https://doh.au.ahadns.net/dns-query?name=blokada.org&type=a&ct=application/dns-json
- https://doh.nl.ahadns.net/dns-query?name=blokada.org&type=a&ct=application/dns-json
- https://doh.no.ahadns.net/dns-query?name=blokada.org&type=a&ct=application/dns-json
Reference:
- https://ahadns.com/dns-over-https/

Add some AhaDNS DNS servers with DNS over https enabled

---

android/gradle/wrapper/gradle-wrapper.properties

- point Android gradle wrapper at the bundled distribution so it doesn't fetch from the network
- `make test` *(fails: Failed to update packages)*
- `timeout 120 make build-android-six-offline` *(fails: Plugin version not found offline)*

attempt offline android build
