- About us.md
About us section has been created
> Create About us.md

- README.md
Also fix some issues on PR #351
> Add warnings about fake websites to README.md

- app/src/flavor-adblocker/kotlin/adblocker/RequestLogger.kt
- app/src/flavor-adblocker/kotlin/flavor/Module.kt
- app/src/legacy/AndroidManifest.xml
- app/src/legacy/kotlin/core/App.kt
- app/src/legacy/res/layout/view_logger_config.xml
- app/src/legacy/res/values/strings_logger.xml
- app/src/tunnel/kotlin/tunnel/Main.kt
- app/src/tunnel/kotlin/tunnel/Proxy.kt
credits @ps100000 
Had to rebase and messed up.
Original: https://github.com/blokadaorg/blokada/pull/395
> CSV request logger added

- app/src/legacy/res/xml/list_widget_info.xml
It's only a small error but some people where annoyed. :man_shrugging:
> Changed the default size of the list widget from 2x3 to 3x2

- app/src/legacy/kotlin/core/bits/Slots.kt
- app/src/legacy/kotlin/core/bits/menu/advanced/MenuAdvanced.kt
- app/src/legacy/res/values/strings_panel.xml
Some people noticed this feature was missing in 4.1 so here it is again. :smiley:
> reimplemented the reset button for the block counter in 4.1

- app/src/legacy/kotlin/core/bits/menu/adblocking/HostsLogVB.kt
- app/src/legacy/res/values/strings_bits.xml
- app/src/tunnel/kotlin/tunnel/Persistence.kt
> Added button for clearing the live history/host log

- app/src/ui-blokada/kotlin/core/StepActivity.kt
- app/src/ui-blokada/kotlin/core/bits/Slots.kt
- app/src/ui-blokada/kotlin/filter/AFilterSources.kt
- app/src/ui-blokada/res/values/strings_panel.xml
Implemented the functionality behind the button "File" in the import dialog in "Ad blocking -> Host Lists".
> Implemented filter import from file

- app/src/core/kotlin/core/Persistence.kt
- app/src/tun-local/kotlin/tunnel/Persistence.kt
- app/src/tun-local/kotlin/tunnel/SmartList.kt
- app/src/ui-blokada/kotlin/core/bits/Slots.kt
This is a bit less side-effects solution for the smart list path problem attempted here: https://github.com/blokadaorg/blokada/pull/577
> Fix storage path for SmartList

- app/src/tun-local/kotlin/tunnel/FilterManager.kt
- app/src/tun-local/kotlin/tunnel/SmartList.kt
- app/src/tun-local/kotlin/tunnel/TunnelMain.kt
- app/src/tun-local/kotlin/tunnel/TunnelModel.kt
- app/src/ui-blokada/kotlin/core/Tunnel.kt
- app/src/ui-blokada/kotlin/core/bits/Slots.kt
- app/src/ui-blokada/res/values/strings_tunnel.xml
New features: 
Additional:
- refactored config presistence
> Smart list V2

- app/src/ui-blokada/kotlin/core/StepActivity.kt
Fixed the bug that if you add a custom black-/whitelist it is always added as a blacklist
> fixed local files always being blacklists

- app/src/core/kotlin/adblocker/ListWidget.kt
- app/src/core/kotlin/core/ControlswitchWidget.kt
- app/src/full/AndroidManifest.xml
- app/src/full/kotlin/flavor/Module.kt
- app/src/google/kotlin/flavor/Module.kt
- app/src/ui-blokada/AndroidManifest.xml
- app/src/ui-blokada/kotlin/notification/ANotificationUtils.kt
- app/src/ui-blokada/kotlin/notification/ANotificationsToggleService.kt
- app/src/ui-blokada/res/layout/widget_controlswitch.xml
- app/src/ui-blokada/res/xml/controlswitch_widget_info.xml
> Switch widgets

- app/src/ui-blokada/kotlin/core/bits/Slots.kt
- app/src/ui-blokada/kotlin/core/bits/menu/apps/AllAppsDashboardSectionVB.kt
- app/src/ui-blokada/res/values/strings_panel.xml
Fixes #494 by allowing a user to whitelist all apps with a one tap.
> added white/blacklist all apps slot to app rule menu

- app/src/full/kotlin/tunnel/BlockaTunnelFiltering.kt
- app/src/full/kotlin/tunnel/DnsProxy.kt
- app/src/tun-local/kotlin/tunnel/Model.kt
- app/src/tun-local/kotlin/tunnel/RequestLog.kt
and fixed a possible out of bounds exception.
> change RequestLog to match based on request id instead of domain

- app/src/core/kotlin/adblocker/ActiveWidget.kt
- app/src/core/kotlin/adblocker/ListWidget.kt
- app/src/ui-blokada/kotlin/core/bits/AdsDashboardSectionVB.kt
- app/src/ui-blokada/res/layout/view_config_widget.xml
- app/src/ui-blokada/res/layout/widget_active.xml
- app/src/ui-blokada/res/values/strings_widget.xml
Changes:
- New option to show VPN gateway name
- New option to always show number of blocked requests in thousands
- Clicking on the widget beside the icon now opens Blokada
- changed list-widget to always show the last 10, distinct, blocked domains
> reworked active widget

- app/src/ui-blokada/kotlin/core/bits/AdsBlockedVB.kt
- app/src/ui-blokada/res/values/strings_bits.xml
> changed counter on dashboard to also display start date

- app/src/ui-blokada/kotlin/filter/HostlineProcessor.kt
> Fixed host line processor ignoring valid lines with end comments

- android5/app/src/main/java/service/StatsService.kt
- android5/app/src/main/java/ui/StatsViewModel.kt
The first commit changes the getStat's denied variable, the other fixes the counter on the main screen to report the correct value of blocked elements (instead of the allowed ones).
> Fixing issue #798

- android5/app/src/main/java/repository/DnsDataSource.kt
Reference:
- https://101.101.101.101/index_en.html
> Add Quad101 IPv6 addresses

- android5/app/src/main/java/repository/DnsDataSource.kt
Reference:
- https://adguard-dns.com/en/public-dns.html
- https://kb.adguard.com/en/general/dns-providers
> Update the IP of AdGuard Family DNS

- android5/app/src/main/java/repository/DnsDataSource.kt
Reference:
- https://www.quad9.net
> Add Quad9 IPv6 addresses

- BUILDING.md
- ios/Gemfile
Some steps I think are necessary when trying to build from scratch.
And one fix for newer ruby missing "abbrev"
> add some more build steps

- common/lib/common/module/rate/actor.dart
- common/lib/common/module/rate/json.dart
- common/lib/common/module/rate/rate.dart
- common/lib/common/module/safari/actor.dart
- common/lib/common/module/safari/value.dart
- common/lib/common/widget/freemium_screen.dart
- common/lib/common/widget/private_dns/private_dns_sheet_android.dart
- common/lib/common/widget/private_dns/private_dns_sheet_ios.dart
- common/lib/common/widget/rate/rate_screen.dart
- common/lib/common/widget/safari/safari_onboard_sheet.dart
- common/lib/common/widget/safari/safari_onboard_yt_sheet.dart
- common/lib/family/widget/add_profile_sheet.dart
- common/lib/family/widget/home/smart_onboard.dart
- common/lib/platform/app/start/start.dart
- common/lib/plus/widget/device_limit_sheet.dart
- common/lib/v6/widget/freemium/weekly_refresh_sheet.dart
- common/pubspec.lock
- common/test/platform/app/start/start_test.dart
The commits aren't really related more than that all is resulting tweaks from running manual testing.
You may want to view each commit diff & description separate to focus on each specific case
> various fixes for issues found in testing
